### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by singhanj13** [tryolabs/luminoth#132]
I was able to start training after running git init, but I had to stop the training mid-way. What I am not clear about is:
1) How do I resume training? The command 'lumi train' does not have any options for that
2) I deleted my 'jobs' folder and restarted training after which I faced the following error:

INFO:tensorflow:Training 273 vars from pretrained module.
/home/ansingh8/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
INFO:tensorflow:Starting training for <luminoth.models.fasterrcnn.fasterrcnn.FasterRCNN object at 0x2ac0b0341910>
INFO:tensorflow:Constructing op to load 520 variables from pretrained checkpoint /home/ansingh8/.luminoth/resnet_v1_101.ckpt
INFO:tensorflow:Create CheckpointSaverHook.
2017-11-23 01:08:28.666546: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Saving checkpoints for 1 into jobs/model.ckpt.
INFO:tensorflow:step: 1, file: n09246464_4013, train_loss: 460.816711426, in 85.67s
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/home/ansingh8/miniconda2/bin/lumi", line 11, in <module>
    sys.exit(cli())
  File "/home/ansingh8/miniconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ansingh8/miniconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ansingh8/miniconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ansingh8/miniconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ansingh8/miniconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ansingh8/miniconda2/lib/python2.7/site-packages/luminoth/train.py", line 249, in train
    config, environment=environment
  File "/home/ansingh8/miniconda2/lib/python2.7/site-packages/luminoth/train.py", line 194, in run
    save_run(config, environment=environment)
  File "/home/ansingh8/miniconda2/lib/python2.7/site-packages/luminoth/utils/experiments.py", line 52, in save_run
    lumi_version = get_luminoth_version()
  File "/home/ansingh8/miniconda2/lib/python2.7/site-packages/luminoth/utils/experiments.py", line 25, in get_luminoth_version
    ['git', 'rev-parse', 'HEAD'], cwd=CURRENT_DIR
  File "/home/ansingh8/miniconda2/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128

**Comment by IanTayler** [comment]
Yes, sorry I didn't foresee this when I told you you could fix it on the spot by running `git init`.

Thankfully, the problem is already solved at master (it's the same problem as #130 ), so if you clone the repository and run `pip install -e .`, it should be working.

If it's absolutely necessary for you to maintain your current installation of luminoth, it is possible you could fix it by running:

```
git add -A
git commit -m "placeholder"
```

But I recommend reinstalling.

> How do I resume training? The command 'lumi train' does not have any options for that

It resumes automatically, reading the latest checkpoint from the `jobs` directory (or whichever directory you set as `train.job_dir` in the config YAML file).
