### ISSUE TITLE
ImportError: cannot import name 'opentype'

### ISSUE THREAD

**Issue by h93910** [tryolabs/luminoth#147]
how to resolve?

this is my pip3 list
DEPRECATION: The default format will
e --format=(legacy|columns) (or defin
f under the [list] section) to disabl
absl-py (0.1.7)
asn1crypto (0.22.0)
bcrypt (3.1.3)
bleach (1.5.0)
cachetools (2.0.1)
certifi (2017.11.5)
cffi (1.10.0)
chardet (3.0.4)
click (6.7)
cryptography (2.0)
dm-sonnet (1.14)
easydict (1.7)
enum34 (1.1.6)
eyeD3 (0.8)
Flask (0.12.2)
google-api-core (0.1.3)
google-api-python-client (1.6.4)
google-auth (1.2.1)
google-cloud-core (0.28.0)
google-cloud-storage (1.6.0)
google-resumable-media (0.3.1)
googleapis-common-protos (1.5.3)
html5lib (0.9999999)
httplib2 (0.10.3)
idna (2.5)
itsdangerous (0.24)
Jinja2 (2.9.6)
luminoth (0.0.2)
lxml (4.1.1)
Markdown (2.6.11)
MarkupSafe (1.0)
numpy (1.14.0)
oauth2client (4.1.2)
paramiko (2.2.1)
Pillow (5.0.0)
pip (9.0.1)
protobuf (3.5.1)
pyasn1 (0.2.3)
pyasn1-modules (0.2.1)
pycparser (2.18)
pygame (1.9.3)
PyMySQL (0.7.11)
PyNaCl (1.1.2)
PyQt5 (5.8.2)
pyqt5-tools (5.8.2.1.0)
pytz (2017.3)
PyYAML (3.12)
requests (2.18.4)
rsa (3.4.2)
setuptools (38.4.0)
sip (4.19.2)
six (1.11.0)
sshtunnel (0.1.2)
tensorflow (1.4.0)
tensorflow-tensorboard (0.4.0rc3)
uritemplate (3.0.0)
urllib3 (1.22)
Werkzeug (0.14.1)
wheel (0.30.0)

**Comment by vierja** [comment]
Hi @h93910,

Can you give us more details on the error (stacktrace) and what platform you are running on?

Thanks.

**Comment by apollo-time** [comment]
I got same error.
Windows 10, Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
```
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\lumi.exe\__main__.py", line 5, in <module>
  File "d:\anaconda3\lib\site-packages\luminoth\__init__.py", line 1, in <module>
    from luminoth.cli import cli  # noqa
  File "d:\anaconda3\lib\site-packages\luminoth\cli.py", line 16, in <module>
    from luminoth.tools import cloud, dataset, server
  File "d:\anaconda3\lib\site-packages\luminoth\tools\__init__.py", line 1, in <module>
    from .cloud import cloud  # noqa
  File "d:\anaconda3\lib\site-packages\luminoth\tools\cloud\__init__.py", line 1, in <module>
    from .cli import cloud  # noqa
  File "d:\anaconda3\lib\site-packages\luminoth\tools\cloud\cli.py", line 3, in <module>
    from .gcloud import gc
  File "d:\anaconda3\lib\site-packages\luminoth\tools\cloud\gcloud.py", line 14, in <module>
    from google.cloud import storage
  File "d:\anaconda3\lib\site-packages\google\cloud\storage\__init__.py", line 40, in <module>
    from google.cloud.storage.client import Client
  File "d:\anaconda3\lib\site-packages\google\cloud\storage\client.py", line 22, in <module>
    from google.cloud.client import ClientWithProject
  File "d:\anaconda3\lib\site-packages\google\cloud\client.py", line 27, in <module>
    from google.oauth2 import service_account
  File "d:\anaconda3\lib\site-packages\google\oauth2\service_account.py", line 77, in <module>
    from google.auth import _service_account_info
  File "d:\anaconda3\lib\site-packages\google\auth\_service_account_info.py", line 22, in <module>
    from google.auth import crypt
  File "d:\anaconda3\lib\site-packages\google\auth\crypt\__init__.py", line 39, in <module>
    from google.auth.crypt import rsa
  File "d:\anaconda3\lib\site-packages\google\auth\crypt\rsa.py", line 17, in <module>
    from google.auth.crypt import _python_rsa
  File "d:\anaconda3\lib\site-packages\google\auth\crypt\_python_rsa.py", line 29, in <module>
    from pyasn1_modules.rfc2459 import Certificate
  File "d:\anaconda3\lib\site-packages\pyasn1_modules\rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
ImportError: cannot import name 'opentype'
```

**Comment by chricke** [comment]
Hi,

i have the same error on Ubuntu with Anaconda - any update on how to fix this?

**Comment by npeirson** [comment]
Thanks @chricke , that fixed it for me too.
