### ISSUE TITLE
AttributeError: 'TruncatedBaseNetwork'

### ISSUE THREAD

**Issue by zyt312074545** [tryolabs/luminoth#167]
While training, I faced the following error. If who know, please help me resolve this?

INFO:tensorflow:Starting training for <luminoth.models.fasterrcnn.fasterrcnn.FasterRCNN object at 0x7f4a19852828>
Traceback (most recent call last):
  File "/home/zyt/.conda/envs/deeplearning/bin/lumi", line 11, in <module>
    sys.exit(cli())
  File "/home/zyt/.conda/envs/deeplearning/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/zyt/.conda/envs/deeplearning/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/zyt/.conda/envs/deeplearning/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zyt/.conda/envs/deeplearning/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zyt/.conda/envs/deeplearning/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/zyt/.conda/envs/deeplearning/lib/python3.6/site-packages/luminoth/train.py", line 272, in train
    config, environment=environment
  File "/home/zyt/.conda/envs/deeplearning/lib/python3.6/site-packages/luminoth/train.py", line 103, in run
    with tf.control_dependencies([model.load_pretrained_weights()]):
  File "/home/zyt/.conda/envs/deeplearning/lib/python3.6/site-packages/luminoth/models/fasterrcnn/fasterrcnn.py", line 368, in load_pretrained_weights
    return self.base_network.load_weights()
  File "/home/zyt/.conda/envs/deeplearning/lib/python3.6/site-packages/luminoth/models/base/base_network.py", line 201, in load_weights
    if self.pretrained_weights_scope:
AttributeError: 'TruncatedBaseNetwork' object has no attribute 'pretrained_weights_scope'

**Comment by joaqo** [comment]
Hey, @zyt312074545 thanks for the bug report. It seems we have introduced an incompatibility between our fasterrcnn and our ssd implementations in our latest 0.1.0 release, we'll fix it asap and release 0.1.1! Will let you know when its fixed and ready for download.
