### ISSUE TITLE
"AttributeError: _replace" error when parsing a config.yml file during training

### ISSUE THREAD

**Issue by ogienma** [tryolabs/luminoth#223]
Hello,

When running `lumi train -c config.yml`, the program exits with an "AttributeError: _replace" message as the config file is being parsed (before the dataset is accessed and the actual training process starts).

Here's what I've tried testing so far:

- Ubuntu 16.04 (via Windows 10 WSL) and Max OS X
- Python 3.6.6
- Luminoth 0.2.1.dev0, 0.2.0, and 0.1.2
- Tensorflow 1.11.0
- Numpy 1.15.2 and 1.13.3
- Configuration: [https://github.com/tryolabs/luminoth/blob/master/examples/sample_config.yml](https://github.com/tryolabs/luminoth/blob/master/examples/sample_config.yml) (I tried a couple of custom ones, too - all have the same error)

The full message is as follows:

```
/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/Users/ogienma/miniconda3/envs/lumi/bin/lumi", line 11, in <module>
    sys.exit(cli())
  File "/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/luminoth/train.py", line 296, in train
    config = get_config(config_files, override_params=override_params)
  File "/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/luminoth/utils/config.py", line 19, in get_config
    model_base_config, custom_config, override_params
  File "/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/luminoth/utils/config.py", line 225, in get_model_config
    return cleanup_config(config)
  File "/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/luminoth/utils/config.py", line 204, in cleanup_config
    config.pop(cleanup_key, None)
  File "/Users/ogienma/miniconda3/envs/lumi/lib/python3.6/site-packages/easydict/__init__.py", line 142, in pop
    delattr(self, k)
AttributeError: _replace
```

**Comment by ogienma** [comment]
I solved this by deleting the config keys in a different way. I replaced https://github.com/tryolabs/luminoth/blob/master/luminoth/utils/config.py#L204 with:
 
```
        try:
            del config[cleanup_key]
        except KeyError:
            pass
```

No idea why that works but `pop` doesn't - that's a legitimate usage of `pop` after all - but there you go.

**Comment by dekked** [comment]
Thanks for the report.

This is caused by a bug in a recent version of a dependency (easydict). I have submitted [this PR](https://github.com/makinacorpus/easydict/pull/14), which hopefully will be merged and released soon. If not, we'll work around this code.
