### ISSUE TITLE
[Error] [Train] : AttributeError: 'NoneType' object has no attribute 'initializer'

### ISSUE THREAD

**Issue by jsdussanc** [tryolabs/luminoth#224]
When train and add `with_rcnn: False` on config.yml 
```Traceback (most recent call last):
  File "/home/inkremental-3/gitKraken/luminoth/venv/bin/lumi", line 9, in <module>
    load_entry_point('luminoth', 'console_scripts', 'lumi')()
  File "/home/inkremental-3/gitKraken/luminoth/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/inkremental-3/gitKraken/luminoth/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/inkremental-3/gitKraken/luminoth/venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/inkremental-3/gitKraken/luminoth/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/inkremental-3/gitKraken/luminoth/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/inkremental-3/gitKraken/luminoth/luminoth/train.py", line 306, in train
    config, environment=environment
  File "/home/inkremental-3/gitKraken/luminoth/luminoth/train.py", line 103, in run
    name='optimizer_slots_initializer'
  File "/home/inkremental-3/gitKraken/luminoth/venv/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 2566, in variables_initializer
    return control_flow_ops.group(*[v.initializer for v in var_list], name=name)
  File "/home/inkremental-3/gitKraken/luminoth/venv/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 2566, in <listcomp>
    return control_flow_ops.group(*[v.initializer for v in var_list], name=name)
AttributeError: 'NoneType' object has no attribute 'initializer'
```

Config.yml:
```
train:
  # Run on debug mode (which enables more logging).
  debug: True
  
  job_dir: jobs/

  run_name: train-dipstick-frcnn-npn
 
dataset:
  type: object_detection
  # From which directory to read the dataset.
  dir: dataset/pascal/tf
  # Which split of tfrecords to look for.
  
model:
  type: fasterrcnn
  network:
    # Total number of classes to predict.
    num_classes: 20
    # Use RCNN or just RPN.
    with_rcnn: False
```

**Comment by sbochkar** [comment]
Had the same problem. Make sure `use_tail` is set to False.
Solved the problem for me.
