### ISSUE TITLE
Issue with luminoth version 0.2.3.dev

### ISSUE THREAD

**Issue by AshwinAce** [tryolabs/luminoth#240]
As far as I can see version 0.2.3 is not out yet, with pip installing version 0.2.2 and `pip install -e .[gcloud]` installing the dev version of 0.2.3. This is the error I get, not sure if it will apply once we get the actual version.
```
Bucket name not specified. Using "luminoth-107908267694143463013".
Found `setup.py` file in "/home/ace/luminoth". Using it instead of shim.
Traceback (most recent call last):
  File "/home/ace/anaconda3/bin/lumi", line 11, in <module>
    load_entry_point('luminoth', 'console_scripts', 'lumi')()
  File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ace/luminoth/luminoth/tools/cloud/gcloud.py", line 87, in decorated_function
    return f(*args, **kwargs)
  File "/home/ace/luminoth/luminoth/tools/cloud/gcloud.py", line 271, in train
    package_path = build_package(bucket, base_path)
  File "/home/ace/luminoth/luminoth/tools/cloud/gcloud.py", line 127, in build_package
    cwd=package_dir, stdout=devnull, stderr=devnull,
UnboundLocalError: local variable 'package_dir' referenced before assignment
```

**Comment by dekked** [comment]
Thanks again @AshwinAce! In the rush to fix for the majority of people (that do not install with -e), this slipped through.

Fortunately, we don't need to release a new version just for this, but will be fixed in master :)

**Comment by AshwinAce** [comment]
Working as of now! Thanks a lot! I used `pip install luminoth` and nothing else.
