### ISSUE TITLE
range() integer end argument expected, got float

### ISSUE THREAD

**Issue by waeldgm** [tryolabs/luminoth#241]
I am simply trying to use luminoth with a simple image but I run into this issue.

Do you know where it might come from?
 
`MBP-de-Wael:luminoth Waelabd$ lumi predict test122.jpg --checkpoint=fast --save-media-to="."
Found 1 files to predict.
2018-11-10 13:12:07.176885: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Predicting test122.jpg...Traceback (most recent call last):
  File "/usr/local/bin/lumi", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/luminoth/predict.py", line 279, in predict
    save_path=save_path,
  File "/usr/local/lib/python2.7/site-packages/luminoth/predict.py", line 94, in predict_image
    vis_objects(np.array(image), objects).save(save_path)
  File "/usr/local/lib/python2.7/site-packages/luminoth/vis.py", line 170, in vis_objects
    draw, obj['bbox'], color, width=round(3 * scale), fill=fill
  File "/usr/local/lib/python2.7/site-packages/luminoth/vis.py", line 75, in draw_rectangle
    for i in range(width):
TypeError: range() integer end argument expected, got float.`

**Comment by cloistermode** [comment]
I also have this issue.

**Comment by dekked** [comment]
Thanks for your report!

I have fixed it in #243. In the meantime, you can use Luminoth with Python 3 (Python 2 support will be removed eventually).
