### ISSUE TITLE
How to install luminoth using Anaconda?

### ISSUE THREAD

**Issue by sliawatimena** [tryolabs/luminoth#86]
I am using Anaconda Navigator 1.6.8 at Windows 7 environment. 
Python 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 10:25:46) [MSC v.1900 64 bit (AMD64)] on win32

How to install luminoth using Anaconda? Or using command prompt?

Thank you very much in advance.

Regards,
Suryadi

**Comment by bhargav333** [comment]
If you want to create locally:
1. Go to command prompt
2. Create conda environment 
    conda create —name environment_name
3. activate environment
      activate environment_name
4.For CPU Support
     pip install luminoth
   For GPU Support
     pip install dm-sonnet-gpu

**Comment by IanTayler** [comment]
Thanks, @bhargav333 !
@sliawatimena , have you managed to install `luminoth` using @bhargav333 's instructions? If so, let me know so that I can close the issue.
Just a little note so that it's absolutely clear, if you want GPU support, after installing `dm-sonnet-gpu` you still need to do `pip install luminoth` to get `luminoth`. Also, doing it the other way around (installing `luminoth` before `dm-sonnet-gpu`) won't work.
As a final note, you should know `luminoth` hasn't been tested in a windows environment yet.

**Comment by sliawatimena** [comment]
Here is my error:
`(E:\Anaconda3\envs\tensorflow) C:\Users\user>pip install luminoth
Collecting luminoth
Exception:
Traceback (most recent call last):
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

(E:\Anaconda3\envs\tensorflow) C:\Users\user>`

**Comment by sliawatimena** [comment]
I tried to clone into e:\github\luminoth
(E:\Anaconda3\envs\tensorflow) E:\Github\luminoth>pip install -e .

The errors:
Obtaining file:///E:/Github/luminoth
Requirement already satisfied: numpy in e:\anaconda3\envs\tensorflow\lib\site-packages (from luminoth==0.0.2.
Collecting Pillow (from luminoth==0.0.2.dev0)
Exception:
Traceback (most recent call last):
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

**Comment by sliawatimena** [comment]
From E:\Github\luminoth\setup.py 
INSTALL_REQUIRES = [
...
    'google-api-python-client>=1.6.2,<2',
    'google-cloud-storage>=1.2.0',
...
]

It need google-api-python-client (from Anaconda Navigator, it shows gdata version 2.0.18).
Can I modified from:  'google-api-python-client>=1.6.2,<2',
into:  'google-api-python-client>=1.6.2,<3',

**Comment by sliawatimena** [comment]
The first attempt using environment with python 3.6, tensorflow installed, but cannot install gdata (that need python 2.6).
The second attempt using environment with python 2.7, but cannot install tensorflow that need python >3.5.

Do I need to wait for gdata porting to python 3.6 first?

**Comment by sliawatimena** [comment]
(E:\Anaconda3\envs\tensorflow) E:\Github\luminoth>lumi --help

Traceback (most recent call last):
  File "E:\Anaconda3\envs\tensorflow\Scripts\lumi-script.py", line 11, in <module>
    load_entry_point('luminoth', 'console_scripts', 'lumi')()
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pkg_resources\__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pkg_resources\__init__.py", line 2751, in load_entry_poin
    return ep.load()
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pkg_resources\__init__.py", line 2405, in load
    return self.resolve()
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "e:\github\luminoth\luminoth\__init__.py", line 1, in <module>
    from luminoth.cli import cli  # noqa
  File "e:\github\luminoth\luminoth\cli.py", line 14, in <module>
    from luminoth.tools import cloud, dataset, server
  File "e:\github\luminoth\luminoth\tools\__init__.py", line 3, in <module>
    from .server import server  # noqa
  File "e:\github\luminoth\luminoth\tools\server\__init__.py", line 1, in <module>
    from .cli import server  # noqa
  File "e:\github\luminoth\luminoth\tools\server\cli.py", line 3, in <module>
    from .web import web
  File "e:\github\luminoth\luminoth\tools\server\web.py", line 8, in <module>
    from luminoth.models import get_model
  File "e:\github\luminoth\luminoth\models\__init__.py", line 1, in <module>
    from .models import get_model  # noqa
  File "e:\github\luminoth\luminoth\models\models.py", line 1, in <module>
    from luminoth.models.fasterrcnn import FasterRCNN
  File "e:\github\luminoth\luminoth\models\fasterrcnn\__init__.py", line 1, in <module>
    from .fasterrcnn import FasterRCNN  # noqa
  File "e:\github\luminoth\luminoth\models\fasterrcnn\fasterrcnn.py", line 5, in <module>
    from luminoth.models.fasterrcnn.rcnn import RCNN
  File "e:\github\luminoth\luminoth\models\fasterrcnn\rcnn.py", line 8, in <module>
    from luminoth.utils.vars import (
  File "e:\github\luminoth\luminoth\utils\vars.py", line 12, in <module>
    'glorot_uniform_initializer': tf.glorot_uniform_initializer,
AttributeError: module 'tensorflow' has no attribute 'glorot_uniform_initializer'

(E:\Anaconda3\envs\tensorflow) E:\Github\luminoth>

**Comment by gastonrod07** [comment]
Hello, which version of Tensorflow do you have installed?

**Comment by sliawatimena** [comment]
Tensorflow 1.2.1. 
Tensorflow-Tensorboard 0.1.6
Using Python 3.6.3

I cannot use: pip install tensorflow --upgrade (from my dos prompt).
How to upgrade to newer tensorflow?
