### ISSUE TITLE
Google Apis Error

### ISSUE THREAD

**Issue by mdblabs** [tryolabs/luminoth#93]
Hi,
I'm trying to install luminoth on Windows 8, and I'm getting an error installing googleapis-common-protos.

Collecting googleapis-common-protos (from gcloud)
  Using cached googleapis-common-protos-1.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mariano-dediego\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "c:\users\mariano-dediego\appdata\local\programs\python\python36\lib\site-packages\setuptools\extern\__init__.py", line 1, in <mo
dule>
        from pkg_resources.extern import VendorImporter
      File "c:\users\mariano-dediego\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3017, in <mod
ule>
        @_call_aside
      File "c:\users\mariano-dediego\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3003, in _cal
l_aside
        f(*args, **kwargs)
      File "c:\users\mariano-dediego\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3045, in _ini
tialize_master_working_set
        dist.activate(replace=False)
      File "c:\users\mariano-dediego\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2577, in acti
vate
        declare_namespace(pkg)
      File "c:\users\mariano-dediego\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2151, in decl
are_namespace
        _handle_ns(packageName, path_item)
      File "c:\users\mariano-dediego\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2091, in _han
dle_ns
        _rebuild_mod_path(path, packageName, module)
      File "c:\users\mariano-dediego\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2120, in _reb
uild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\MARIAN~1\AppData\Local\Temp\pip-build-_ld46zq1\googleapis-common-pro 

Any idea?

My platform: 
Windows 8
Python 3.6.3
Pip 9.0.1

Thank you very much.

**Comment by IanTayler** [comment]
Hi, @mdblabs !
I think this could be a problem with setuptools, based on [this issue](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2990).

Try running `pip install --upgrade setuptools` and tell me if that fixes the problem.

You may want to check out [this setuptools issue](https://github.com/pypa/setuptools/issues/885) as well.

I'm closing the issue because it doesn't seem to be a problem with luminoth in particular, but let me know if upgrading `setuptools` works anyway.

**Comment by mdblabs** [comment]
Thank you very much @IanTayler!
Now is working.
